[http.routers]
  [http.routers.sprinkler-rtr]
      entryPoints = ["https"]
      rule = "Host(`sprinkler.example.com`)"
      service = "sprinkler-svc"
      middlewares = ["chain-no-auth"]
      [http.routers.sprinkler-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.sprinkler-svc]
    [http.services.sprinkler-svc.loadBalancer]
      passHostHeader = true
      [[http.services.sprinkler-svc.loadBalancer.servers]]
        url = "http://192.168.1.109"
