[http.routers]
  [http.routers.unifi-rtr]
      entryPoints = ["https"]
      rule = "Host(`unifi.example.com`)"
      service = "unifi-svc"
      middlewares = ["chain-no-auth"]
      [http.routers.unifi-rtr.tls]
        certresolver = "dns-cloudflare"

[http.services]
  [http.services.unifi-svc]
    [http.services.unifi-svc.loadBalancer]
      passHostHeader = true
      [[http.services.unifi-svc.loadBalancer.servers]]
        url = "https://192.168.1.108:8443"
